version: '3.7'
services:
  ggcombatcarnage:
    image: freekers/docker-ggcombatcarnage:latest
    container_name: ggcombatcarnage
    restart: always
    volumes:
	 - /opt/gasguzzlers/gamedir:/home/user/Steam
    ports:
      - 3555:3555/udp
      - 3555:3555/tcp
