name: Build and Push Docker Image
on: 
 push:
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 11 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Variable Substitution
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["**/*.sh"]'
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: freekers/docker-ggcombatcarnage:latest,freekers/docker-ggcombatcarnage:${{ github.run_number }}
